// <auto-generated />
namespace FinalProgramacionWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class elimineindicesredundantesyagreguevirtualalosobjetosrelacionales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(elimineindicesredundantesyagreguevirtualalosobjetosrelacionales));
        
        string IMigrationMetadata.Id
        {
            get { return "202207251810163_elimine-indices-redundantes-y-agregue-virtual-a-los-objetos-relacionales"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
