// <auto-generated />
namespace FinalProgramacionWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Tabla_Proveedor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tabla_Proveedor));
        
        string IMigrationMetadata.Id
        {
            get { return "202207182228041_Tabla_Proveedor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
