// <auto-generated />
namespace FinalProgramacionWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class arreglofechasasqldatetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(arreglofechasasqldatetime));
        
        string IMigrationMetadata.Id
        {
            get { return "202207260110202_arreglo-fechas-a-sqldatetime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
